package conf

const (
	BOX_DATABASE_SYSTEM   = "postgres"
	BOX_DEFAULT_HOST      = ""
	POSTGRES_DEFAULT_PORT = 5432
	BOX_DEFAULT_DATABASE  = "logger"
	BOX_DEFAULT_USERNAME  = ""
	BOX_DEFAULT_PASSWORD  = ""

	HOUSE_DEFAULT_HOST     = ""
	HOUSE_DEFAULT_PORT     = 9000
	HOUSE_DEFAULT_DATABASE = "CRTA"
	HOUSE_DEFAULT_USERNAME = ""
	HOUSE_DEFAULT_PASSWORD = ""
)
